"""Render a visual spec as an Azure DevOps (or Jira) work item."""

from __future__ import annotations

import json


def _filter_line(f: dict) -> str:
    name = f.get("name") or "(unmapped field)"
    return f"{name} {f['operator'].lower()} [{', '.join(f['values'])}]"


def _time_line(t: dict) -> str:
    if t["filterType"] == "RelativeDate":
        op = {"InLast": "in the last", "InThis": "in this", "InLastCalendar": "in the last calendar"}[t["operator"]]
        unit = t["timeUnit"].lower()
        n = t["timeUnitsCount"]
        unit = unit[:-1] if n == 1 else unit
        s = f"{op} {n} {unit}" if t["operator"] == "InLast" else f"{op} {unit}"
        return s + (" (to date)" if t.get("toDate") else "")
    return t["text"]


def to_work_item(spec: dict, area_path: str = "Clinical Analytics\\Dashboards") -> dict:
    criteria = [f"Visual type is **{spec['powerbi_visual']}** ({spec['chart_type'].replace('_', ' ')})."]
    for m in spec["measures"]:
        criteria.append(f"Shows **{m['name']}** (`{m['field'] or 'TBD'}`, aggregation: {m['aggregation']}).")
    if spec["group_by"]:
        criteria.append("Grouped by " + ", ".join(f"**{g['name']}**" for g in spec["group_by"]) + ".")
    if spec["series"]:
        criteria.append("Split/legend by " + ", ".join(f"**{s['name']}**" for s in spec["series"]) + ".")
    for f in spec["filters"]:
        criteria.append(f"Filter: {_filter_line(f)}.")
    if spec["time_filter"]:
        criteria.append(f"Date filter: {_time_line(spec['time_filter'])} on `{spec['time_filter']['field']}`.")
    if spec["top_n"]:
        t = spec["top_n"]
        criteria.append(f"Top N filter: {'top' if t['direction'] == 'desc' else 'bottom'} {t['n']} by {t['by']}.")
    if spec["sort"]:
        criteria.append(f"Sorted by {spec['sort']['by']} ({spec['sort']['direction']}).")

    description = (
        f"**Original request:** \"{spec['source_text']}\"\n\n"
        f"**Proposed visual:** {spec['title']}\n\n"
        "Generated by iVIS. Please confirm field mappings before building."
    )
    if spec["warnings"]:
        description += "\n\n**Open questions:**\n" + "\n".join(f"- {w}" for w in spec["warnings"])

    return {
        "System.WorkItemType": "User Story",
        "System.Title": f"[Dashboard] {spec['title']}",
        "System.AreaPath": area_path,
        "System.Tags": "iVIS; PowerBI; " + spec["chart_type"],
        "System.Description": description,
        "Microsoft.VSTS.Common.AcceptanceCriteria": "\n".join(f"- {c}" for c in criteria),
        "iVIS.Spec": json.dumps(spec, ensure_ascii=False),
    }


def to_markdown(spec: dict) -> str:
    wi = to_work_item(spec)
    return (
        f"### {wi['System.Title']}\n\n{wi['System.Description']}\n\n"
        f"#### Acceptance criteria\n{wi['Microsoft.VSTS.Common.AcceptanceCriteria']}\n"
    )


def to_json_patch(spec: dict) -> list[dict]:
    """Body for ``POST .../_apis/wit/workitems/$User%20Story?api-version=7.1`` (json-patch)."""
    wi = to_work_item(spec)
    return [{"op": "add", "path": f"/fields/{k}", "value": v} for k, v in wi.items() if not k.startswith("iVIS.")]
